// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAN6U3Ws0Q8jBYpiRJt9glDKt2mJ9lyDE',
    appId: '1:124511145427:android:70269e0c037285a12f3326',
    messagingSenderId: '124511145427',
    projectId: 'obroomart-3a2c3',
    storageBucket: 'obroomart-3a2c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH03l3vg-QcwXxG3vQPjG926W-k4VLWQY',
    appId: '1:124511145427:ios:b14705120fe0a7192f3326',
    messagingSenderId: '124511145427',
    projectId: 'obroomart-3a2c3',
    storageBucket: 'obroomart-3a2c3.appspot.com',
    androidClientId: '124511145427-47g5a55h8p49m83s5treh2g1ai6nitfa.apps.googleusercontent.com',
    iosClientId: '124511145427-13dgko1snt9oc1rre8778mphqqo85q3h.apps.googleusercontent.com',
    iosBundleId: 'com.obroomart.obroomart',
  );
}
